# Generated by Django 3.0.3 on 2020-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_test', models.CharField(max_length=30)),
                ('key_prod', models.CharField(max_length=30)),
                ('key_type', models.CharField(max_length=30)),
                ('key_user', models.CharField(max_length=10)),
                ('key_kcv', models.CharField(max_length=7)),
            ],
        ),
    ]
