# Generated by Django 3.0.3 on 2020-03-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_keys_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='key_prod',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='key_test',
        ),
    ]
