# Generated by Django 3.0.3 on 2020-03-26 10:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20200326_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('test', 'test'), ('prod', 'prod')], max_length=9),
        ),
    ]
