# Generated by Django 3.0.3 on 2020-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20200326_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='title',
            new_name='choice',
        ),
        migrations.AddField(
            model_name='keys',
            name='key_type',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
