# Generated by Django 3.0.3 on 2020-03-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20200326_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='key',
        ),
    ]
