# Generated by Django 3.0.3 on 2020-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_keys_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='key',
        ),
    ]
