# Generated by Django 3.0.3 on 2020-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_remove_keys_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='key',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
